version: "3.7"
services:

  postgres:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo

  demo-rest:
    build: ./
    ports:
      - 8080:8080
    links:
      - postgres
